### ISSUE TITLE
Maximum of array under 'deaths' does not match the value in 'tot_deaths'

### ISSUE THREAD

**Issue by RudrakshTuwani** [Yu-Group/covid19-severity-prediction#13]
The maximum value mentioned in the array under deaths column does not match the total number of deaths for some counties. In total, I found 16 such instances. 

The FIPS codes of the problematic counties are as follows:
`
['01031', '01077', '02110', '05031', '05061', '08069', '08097', '13085', '13269', '28005', '39027', '39113', '45023', '49005', '53037', '54055']
`

I am using the 'abridged' version of the dataset.

**Comment by RudrakshTuwani** [comment]
I did some more digging and found some counties for which the array under `deaths` column is not always increasing. The FIPS codes are as follows:

`
['06047', '08015', '08041', '08123', '09007', '11001', '12019', '12095',
'12099', '12101', '13033', '13095', '13111', '13149', '13177', '13189',
'13243', '13261', '13273', '13275', '13277', '17089', '22007', '22017',
'22045', '22075', '22077', '22087', '22093', '22105', '22109', '22117',
'24003', '24005', '24009', '24013', '24017', '24021', '24025', '24027',
'24031', '24033', '24037', '24043', '24510', '26087', '26147', '28117',
'29099', '30053', '34041', '36005', '36061', '36085', '36121', '37069',
'37101', '39025', '39035', '39049', '39057', '42037', '42043', '42101',
'42115', '45041', '45069', '45079', '47073', '48441', '50027', '51009',
'51013', '51041', '51087', '51127', '51197', '51595', '51760', '53005',
'53035', '53053', '53073']
`

**Comment by shifwang** [comment]
So that's indeed an issue in both the usafacts data and the nytimes data, the cumulative #deaths/cases is not monotonic. Usafacts did not articulate why this happens. According to nytimes, it says "In some cases, the number of cases or deaths for a state or county will decline. This can occur when a state or county corrects an error in the number of cases or deaths they've reported in the past, or when a state moves cases from one county to another. When we are able, we will historically revise counts for all impacted dates. In other cases, this will be reflected in a single-day drop in the number of cases or deaths.".

**Comment by RudrakshTuwani** [comment]
Alright, thanks for the info! 

What is the best way to resolve this? Simply, change the death count for that day to what it was for the preceding day?

**Comment by shifwang** [comment]
I would say the most recent day is the most accurate so cap casts/deaths for any other day using the most recent day.
